### ISSUE TITLE
Can the mediator live data updates be postponed till both (n) values are present?

### ISSUE THREAD

**Issue by abdurahmanadilovic** [Zhuinden/livedata-combinetuple-kt#1]
Awesome lib, one question though, looking at the source code it seems like the value of mediator live data is set after each individual value is updated, can it be made "safe" by updating its value once all values are available?

**Comment by Zhuinden** [comment]
Hello and thank you for your interest, the trick is that the lib is optimized to eliminate the `addSource` and `.value` clutter that is best presented by Google's iosched sample:

https://github.com/google/iosched/blob/4054aa3f8934b8b1208d5823fdbf531a8eb367af/mobile/src/main/java/com/google/samples/apps/iosched/ui/sessiondetail/SessionDetailViewModel.kt#L127-L128

https://github.com/google/iosched/blob/4054aa3f8934b8b1208d5823fdbf531a8eb367af/mobile/src/main/java/com/google/samples/apps/iosched/ui/sessiondetail/SessionDetailViewModel.kt#L183-L188


https://github.com/google/iosched/blob/4054aa3f8934b8b1208d5823fdbf531a8eb367af/mobile/src/main/java/com/google/samples/apps/iosched/ui/sessiondetail/SessionDetailViewModel.kt#L487-L489

But in order to do that, I need to obey LiveData's own contract, which is that `null` values are allowed. 

In that case, I cannot distinguish between whether a LiveData was not initialized, or it was explicitly set to `null`, when I call `mediator.setValue(TupleN(f1.value, f2.value, ..., fN.value))`.

And if I do start doing that, then `Pair<T1?, T2?>` would rather be `Pair<T1, T2>?` as I would not be able to set an initial value if I encountered any `null` values when invoking `f1.value`.

------

So the short answer is that `liveData.setValue(null)` is perfectly valid, I cannot reliably tell when "all values are available", which is why I opted for a `TupleN<T1?, ..., TN?>` approach.

Maybe there's some option I'm not thinking of, but I didn't want to make assumptions, consume valid nulls, etc. in the library itself.

**Comment by Zhuinden** [comment]
If you check another library that offered similar functionality, they actually ran into this problem of "assuming non-null values", and it causes crashes: https://github.com/adibfara/Lives/issues/20

**Comment by abdurahmanadilovic** [comment]
That does make sense, its a simpler implementation from the library point of view. Another question I have is how did you create the 2-16 arity functions, did you write some code to automatically create n arity funciton? :D

**Comment by Zhuinden** [comment]
> I have is how did you create the 2-16 arity functions, did you write some code to automatically create n arity funciton? :D

I only tend to write code generators if [it's less investment than just writing the code](https://xkcd.com/1319/); in second scenario I prefer to use templates, or copy paste + find/replace regex.

In this case due to the dynamic nature of the arguments, I went with copy paste + find/replace regex (with `in selection` on). Android Studio still remembers what it looks like:

![image](https://user-images.githubusercontent.com/11718392/78283706-79229680-751e-11ea-880f-ac7b300fd34c.png)

![image](https://user-images.githubusercontent.com/11718392/78283754-8f305700-751e-11ea-875b-8bec8c6f6344.png)

The typed-ness of the tuples is so nice that it even caught when I accidentally first wrote `Tuple10$1t8, t9, t10` because the number of arguments and the type was wrong.

So I technically wrote it up to 6-arity by hand, and then it was safer to use regex for the rest.

So you can copy-paste for 6, change the arguments to 7 with the new type, rewrite existing code to handle for Tuple7, then add one more `addSource` to handle the 7th LiveData. 

I think I wrote this lib in about an hour. If I had written it up to 32-arity then I probably would have used code gen.

**Comment by Zhuinden** [comment]
I'm surprised I had closed this, but technically solved in https://github.com/Zhuinden/livedata-combinetuple-kt/commit/d5aeada86d3c9106ce715e107333bcc9b25383a4 .
